- example/public/404.html
- example/public/index.html
- example/src/data/documentation.js
- package.json
- src/components/ControlledMenu.js
- src/components/Menu.js
- src/components/MenuItem.js
- src/components/__tests__/ControlledMenu.test.js
- src/components/__tests__/Menu.test.js
- src/components/useMenuList.js
- src/utils/propTypes.js
- Add portal prop
- Add portal testing
- Update documentation
> Feature: add portal prop

- example/src/data/documentation.js
- package.json
- src/components/__tests__/ControlledMenu.test.js
- src/components/__tests__/Menu.test.js
- src/components/__tests__/MenuItem.test.js
- src/components/useMenuList.js
- types/index.d.ts
- Add keepOpen in events for customising when menu is closed
- Add testing and document of keepOpen event property
> Feature: keepOpen event prop for customising when menu is closed

- example/src/utils/index.js
- package.json
- src/__tests__/ControlledMenu.test.js
- src/__tests__/SubMenu.test.js
- src/__tests__/utils/index.js
- src/components/SubMenu.js
- Fix submenu flicking when it's open and anchor item is clicked
- Add testing for MenuList isClosing state
> Fix: submenu flicking

- example/package-lock.json
- package-lock.json
- package.json
- src/__tests__/ControlledMenu.test.js
- src/components/MenuList.js
- src/components/SubMenu.js
- src/components/useMenuList.js
This PR fixes menu detaching from anchor when menu and its anchor are in two different scrollable containers. https://github.com/szhsin/react-menu/issues/59#issuecomment-786460062
>  Fix menu detaching from anchor

- example/src/components/Usage.js
- example/src/data/codeExamples.js
- example/src/data/documentation.js
- example/src/styles/_example.scss
- example/src/styles/_menu.scss
- example/src/styles/index.scss
- package-lock.json
- package.json
- src/__tests__/MenuGroup.test.js
- src/components/MenuGroup.js
- src/components/MenuHeader.js
- src/components/MenuList.js
- src/components/useMenuList.js
- src/index.js
- src/styles/core.scss
- src/utils/cloneChildren.js
- src/utils/constants.js
- src/utils/index.js
- src/utils/utils.js
- types/index.d.ts
- Add `MenuGroup` component
- Allow fix-positioned items in long scrolling menus (#111)
> Feature: menu group

- dist/es/components/SubMenu.js
- dist/es/hooks/useItemState.js
- dist/index.js
- example/src/utils/index.js
- package.json
- src/__tests__/MenuItem.test.js
- src/__tests__/SubMenu.test.js
- src/__tests__/styling.test.js
- src/components/SubMenu.js
- src/hooks/useItemState.js
- Paralleled the changes in #401 for `<SubMenu/>`
- Fixed some edge case bugs
- Updated unit tests
> Hover submenu using `onMouseMove` event

- dist/core.css
- dist/es/components/Menu.js
- dist/es/components/MenuList.js
- dist/es/components/SubMenu.js
- dist/es/hooks/useItemEffect.js
- dist/es/hooks/useItems.js
- dist/es/hooks/useMenuState.js
- dist/es/hooks/useMenuStateAndFocus.js
- dist/es/utils/constants.js
- dist/index.css
- dist/index.js
- package-lock.json
- package.json
- src/components/Menu.js
- src/components/MenuButton.js
- src/components/MenuList.js
- src/components/SubMenu.js
- src/hooks/useItemEffect.js
- src/hooks/useItems.js
- src/hooks/useMenuState.js
- src/hooks/useMenuStateAndFocus.js
- src/styles/core.scss
- src/utils/constants.js
- types/index.d.ts
- Refactor `useMenuState`
- Small bug fixes
> Code refactor and bug fixes

- package-lock.json
- package.json
- types/index.d.ts
Fix incompatible `children` type definition with @types/react "^18"
> Fix incompatible `children` type definition

- dist/es/components/MenuList.js
- dist/es/components/SubMenu.js
- dist/index.js
- package.json
- src/__tests__/SubMenu.test.js
- src/components/MenuList.js
- src/components/SubMenu.js
Keep submenu open in the same direction before reversing (right to left/left to right) until it reaches view boundary
> Submenu to open in consistent directions

- dist/core.css
- dist/es/components/ControlledMenu.js
- dist/es/components/FocusableItem.js
- dist/es/components/MenuButton.js
- dist/es/components/MenuItem.js
- dist/es/components/MenuList.js
- dist/es/components/SubMenu.js
- dist/index.css
- dist/index.js
- example/src/components/Usage.js
- example/src/data/styleGuide.js
- example/src/utils/index.js
- src/__tests__/ControlledMenu.test.js
- src/__tests__/Menu.test.js
- src/__tests__/MenuItem.test.js
- src/__tests__/SSR.test.js
- src/__tests__/SubMenu.test.js
- src/__tests__/utils.js
- src/components/ControlledMenu.js
- src/components/FocusableItem.js
- src/components/MenuButton.js
- src/components/MenuItem.js
- src/components/MenuList.js
- src/components/SubMenu.js
- src/styles/core.scss
- Add an element for focusing menu
- Move some position css from external files to inline styles
> Fix: focus element and inline styles

- dist/es/components/ControlledMenu.js
- dist/es/components/MenuList.js
- dist/es/components/SubMenu.js
- dist/es/hooks/useItemEffect.js
- dist/es/hooks/useItems.js
- dist/es/utils/propTypes.js
- dist/es/utils/utils.js
- dist/index.js
- example/package-lock.json
- example/src/utils/index.js
- package.json
- src/__tests__/SubMenu.test.js
- src/__tests__/utils.js
- src/components/MenuList.js
- src/hooks/useItemEffect.js
- src/hooks/useItems.js
- src/utils/utils.js
Fix menu losing focus and cannot be closed in situations where a focused menu item is removed or disabled.
> fix: menu losing focus

- dist/es/components/FocusableItem.js
- dist/es/components/MenuItem.js
- dist/es/components/SubMenu.js
- dist/es/hooks/useItemState.js
- dist/index.js
- example/src/components/RightSection.js
- example/src/components/Usage.js
- example/src/data/codeExamples.js
- package.json
- src/__tests__/Menu.test.js
- src/__tests__/MenuItem.test.js
- src/__tests__/SubMenu.test.js
- src/__tests__/styling.test.js
- src/components/FocusableItem.js
- src/components/MenuItem.js
- src/components/SubMenu.js
- src/hooks/useItemState.js
Use pointer instead of mouse events for better compatibility on touch screens.
> feat: pointer events

- README.md
- dist/es/components/ControlledMenu.js
- dist/es/components/FocusableItem.js
- dist/es/components/Menu.js
- dist/es/components/MenuItem.js
- dist/es/components/MenuList.js
- dist/es/components/SubMenu.js
- dist/es/hooks/useBEM.js
- dist/es/hooks/useCombinedRef.js
- dist/es/utils/constants.js
- dist/es/utils/utils.js
- dist/es/utils/withHovering.js
- dist/index.js
- example/src/data/codeExamples.js
- example/src/utils/index.js
- src/__tests__/Menu.test.js
- src/__tests__/MenuItem.test.js
- src/components/ControlledMenu.js
- src/components/FocusableItem.js
- src/components/Menu.js
- src/components/MenuItem.js
- src/components/MenuList.js
- src/components/SubMenu.js
- src/hooks/useBEM.js
- src/hooks/useCombinedRef.js
- src/utils/constants.js
- src/utils/utils.js
- src/utils/withHovering.js
- Code refactoring
- Update docs and readme
> chore: refactor

- dist/es/components/Menu.js
- dist/es/hooks/useClick.js
- dist/es/hooks/useHover.js
- dist/es/index.js
- dist/index.js
- example/src/components/Example.js
- example/src/components/Usage.js
- example/src/data/codeExamples.js
- example/src/data/documentation.js
- example/src/utils/index.js
- package-lock.json
- package.json
- src/__tests__/ControlledMenu.test.js
- src/components/Menu.js
- src/components/MenuContainer.js
- src/hooks/index.js
- src/hooks/useClick.js
- src/hooks/useHover.js
- src/index.js
- types/index.d.ts
- Add `useClick` and `useHover` hook.
- Replace toggle click workaround with `useClick`.
> feat: new menu hooks

- dist/es/components/MenuList.js
- dist/index.js
- example/src/components/Usage.js
- example/src/data/codeExamples.js
- example/src/data/documentation.js
- src/__tests__/Menu.test.js
- src/components/MenuList.js
- types/index.d.ts
- Allowing `children` of menu to support render prop pattern.
> feat: menu render prop

- example/src/components/Usage.js
- example/src/data/codeExamples.js
Thanks for the library!
I found a couple of typos in the examples so thought I'd put up a PR to fix them.
> fix: Example typos

- src/utils/utils.js
> fix: added condition to fix exception when opening menu in popout window

- example/src/components/Logo.js
> docs: version menu

- README.md
- dist/es/components/Menu.js
- dist/es/components/MenuItem.js
- dist/es/components/SubMenu.js
- dist/index.js
- example/package-lock.json
- example/src/data/codeExamples.js
- example/src/styles/index.scss
- package-lock.json
- package.json
- src/__tests__/Menu.test.js
- src/components/Menu.js
- src/components/MenuItem.js
- src/components/SubMenu.js
- Prevent default action from "Enter" key events
> fix: enter key

- dist/es/components/MenuList.js
- dist/es/utils/submenuCtx.js
- dist/index.js
- src/components/MenuList.js
- Do not set focus on menu after unmounted
> fix: null ref

- dist/es/components/MenuGroup.js
- dist/es/components/MenuList.js
- dist/es/positionUtils/getNormalizedClientRect.js
- dist/es/positionUtils/getPositionHelpers.js
- dist/index.js
- dist/style-utils/index.cjs.js
- dist/style-utils/index.js
- dist/transitions/zoom.css
- example/package-lock.json
- example/src/data/documentation.js
- example/src/data/styleGuide.js
- example/src/pages/_app.js
- example/src/utils/index.js
- package-lock.json
- package.json
- src/__tests__/Menu.test.js
- src/__tests__/style-utils.test.js
- src/components/ControlledMenu.js
- src/components/MenuGroup.js
- src/components/MenuList.js
- src/positionUtils/getNormalizedClientRect.js
- src/positionUtils/getPositionHelpers.js
- src/positionUtils/index.js
- src/style-utils/index.js
- src/styles/transitions/zoom.scss
- types/index.d.ts
- types/style-utils.d.ts
- Normalize menu dimension when css-transformed
- Include `align` into menu modifiers
- Add `zoom` transition
> feat: normalize css transform

- dist/es/components/MenuList.js
- dist/es/utils/utils.js
- dist/index.js
- example/package-lock.json
- example/src/components/Example.js
- example/src/data/codeExamples.js
- example/src/data/documentation.js
- example/src/utils/index.js
- package-lock.json
- package.json
- src/components/MenuList.js
- types/index.d.ts
- Reposition menu after anchor size has changed
- Fix infinite repositioning when overflow causes menu to resize
> fix: reposition

- dist/es/components/MenuList.js
- dist/es/utils/constants.js
- dist/index.js
- example/package-lock.json
- example/src/utils/index.js
- package-lock.json
- package.json
- src/components/MenuList.js
- src/utils/constants.js
- Fix aria errors in the latest Chrome version (127.0.6533.89)
> fix: aria errors

- package.json
- types/tsconfig.json
- Update type checking scripts
> chore: types

- babel.config.js
- dist/es/components/Menu.js
- eslint.config.mjs
- package-lock.json
- package.json
- Use the flat config with react-hooks-addons
- Remove proposal babel plugins
> chore: config update

- dist/es/components/ControlledMenu.js
- dist/es/components/MenuDivider.js
- dist/es/components/MenuHeader.js
- dist/es/components/MenuList.js
- dist/es/hooks/useItems.js
- dist/es/utils/constants.js
- dist/index.js
- dist/style-utils/index.cjs.js
- dist/style-utils/index.js
- example/gh-pages.sh
- example/package-lock.json
- example/package.json
- example/src/data/documentation.js
- example/src/styles/_basis.scss
- example/src/utils/index.js
- jest.config.js
- package-lock.json
- package.json
- setup-jest.js
- src/__tests__/Menu.test.js
- src/__tests__/SubMenu.test.js
- src/__tests__/utils.js
- src/components/MenuList.js
- src/hooks/useItems.js
- src/utils/constants.js
- types/index.d.ts
- Fix focus element accessibility violation (axe) 
- Deprecate `focusProps`
> fix: axe violations

- package-lock.json
- package.json
- Apply temporary fix for Punycode warning in Node 22
> chore: punycode warning 
